properties:
  - type: secure
    name: apikey
    value: ${API_KEY}
triggers:
  - type: git
    branch: main
    events:
      pull_request: true
    name: Git Trigger - 0
    eventListener: gitlab-pr-listener
    properties:
      - type: secure
        name: TF_VAR_ibmcloud_api_key
        value: ${API_KEY}
      - type: text
        name: tf-dir
        value: sample
    service: ${terraform-template}
inputs:
  - type: git
    path: .tekton
    branch: master
    service: ${schematics-pipeline}
  - type: git
    path: cra
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: git
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: toolchain
    branch: master
    service: ${tekton-catalog}
