properties:
  - type: text
    name: WORKSPACE_ID
    value: ${WORKSPACE_ID}
  - type: secure
    name: apikey
    value: ${API_KEY}
triggers:
  - type: git
    branch: main
    events:
      pull_request: true
    name: Git Trigger - 0
    eventListener: gitlab-pr-listener
    properties:
      - type: secure
        name: TF_VAR_ibmcloud_api_key
        value: ${API_KEY}
      - type: text
        name: tf-dir
        value: sample
    service: ${terraform-template}
inputs:
  - type: git
    path: .tekton
    branch: main
    service: ${schematics-tekton}
