properties:
  - type: text
    name: WORKSPACE_ID
    value: ${WORKSPACE_ID}
  - type: secure
    name: apikey
    value: ${API_KEY}
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
inputs:
  - type: git
    path: .tekton
    branch: master
    service: ${schematics-tekton}
