properties:
  - type: text
    name: WORKSPACE_ID
    value: ${WORKSPACE_ID}
  - type: secure
    name: apikey
    value: ${API_KEY}
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
  - type: git
    branch: main
    events:
      commit: true
    name: Git Trigger - 0
    eventListener: ${event-ci-listener-name}
inputs:
  - type: git
    path: .tekton
    branch: master
    service: ${schematics-pipeline}
