properties:
  - type: text
    name: WORKSPACE_ID
    value: ${WORKSPACE_ID}
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: text
    name: branchForManualTrigger
    value: ${BRANCH}
  - type: text
    name: repositoryForManualTrigger
    value: ${REPOSITORY}
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
    properties:
      - type: text
        name: tf-dir
        value: sample
inputs:
  - type: git
    path: .tekton
    branch: main
    service: ${schematics-tekton}
