apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: WORKSPACE_ID
      description: the workspace id
    - name: API_KEY
      description: the ibmcloud api key
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: WORKSPACE_ID
            value: $(params.WORKSPACE_ID)
          - name: API_KEY
            value: $(params.API_KEY)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/DavidLopezIBM/schematics-tekton"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
