apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: WORKSPACE_ID
      description: the workspace id
    - name: API_KEY
      description: the ibmcloud api key
    - name: repository
      description: The git repo
    - name: branch
      description: branch
    - name: repository-integration
      description: the repo integration name
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: commit timestamp
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: project-id
      description: project id
      default: ""
    - name: tf-dir
      description: the directory where the terraform main entry file is found
      default: ""
    - name: policy-config-json
      description: Configure policies to control thresholds
      default: ""
    - name: tf-var-file
      description: (optional) terraform var-file
      default: ""
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: WORKSPACE_ID
            value: $(params.WORKSPACE_ID)
          - name: API_KEY
            value: $(params.API_KEY)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: repository-integration
            value: $(params.repository-integration)
          - name: commit-id
            value: $(params.commit-id)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: scm-type
            value: $(params.scm-type)
          - name: project-id
            value: $(params.project-id)
          - name: tf-dir
            value: $(params.tf-dir)
          - name: policy-config-json
            value: $(params.policy-config-json)
          - name: tf-var-file
            value: $(params.tf-var-file)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/DavidLopezIBM/schematics-tekton"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-ci-binding
spec:
  params:
    - name: branch
      value: $(event.ref)
    - name: commit-id
      value: $(event.after)
    - name: commit-timestamp
      value: $(event.repository.updated_at)
    - name: repository
      value: $(event.repository.html_url)
    - name: scm-type
      value: "github"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-ci-listener
spec:
  triggers:
    - bindings:
        - name: github-ci-binding
      template:
        name: ci-template
