apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  workspaces:
    - name: pipeline-ws
  params:
    - name: API_KEY
      description: the ibmcloud api key
    - name: WORKSPACE_ID
      description: the workspace id
  tasks:
    - name: update-workspace
      taskRef:
        name: update-workspace-task
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: API_KEY
          value: $(params.API_KEY)
    - name: plan
      runAfter: [update-workspace]
      taskRef:
        name: plan-task
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: API_KEY
          value: $(params.API_KEY)
    - name: apply
      runAfter: [plan]
      taskRef:
        name: apply-task
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: API_KEY
          value: $(params.API_KEY)
    - name: test
      runAfter: [apply]
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      taskRef:
        name: test-task
