apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: API_KEY
      description: the ibmcloud api key
    - name: WORKSPACE_ID
      description: the workspace id
  tasks:
    - name: update-workspace
      taskRef:
        name: update-workspace-task
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: API_KEY
          value: $(params.API_KEY)
    - name: plan
      runAfter: [Update-Workspace]
      taskRef:
        name: plan-task
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: API_KEY
          value: $(params.API_KEY)
    - name: apply
      runAfter: [plan]
      taskRef:
        name: apply-task
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: API_KEY
          value: $(params.API_KEY)
    - name: test
      runAfter: [apply]
      taskRef:
        name: test-task
