---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-pr-listener
spec:
  triggers:
    - bindings:
        - name: gitlab-pr-binding
      template:
        name: pr-template
